openapi: 3.0.3
info:
  description: The Courses API provides a simple interface for applications that want to retrieve lists of courses or information relating to a specific course within Cardiff University. Using the Courses API, clients can filter courses by school, language, level and year.
  version: v1
  title: CoursesApi Assessments Test API
  termsOfService: http://www.cardiff.ac.uk/terms/
  contact:
    name: integration@cardiff.ac.uk
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
- url: https://api.data.cardiff.ac.uk/courses/v1
security:
- default: []
tags:
- name: Test
paths:
  /test:
    get:
      parameters:
      - name: in
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        '200':
          description: ok
      security:
      - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      tags:
      - Test
components:
  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          scopes:
            clearing: Allows users to see clearing data.
          authorizationUrl: https://api.data.cardiff.ac.uk/authorize
