openapi: 3.0.1
info:
  title: EchoTest
  version: v1
servers:
- url: https://api.data.cardiff.ac.uk/echo/v1
security:
- default: []
paths:
  /*:
    get:
      parameters:
      - name: in
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        '200':
          description: OK
      security:
      - default: []
      x-auth-type: None
      x-throttling-tier: Unlimited
  /test:
    get:
      parameters:
      - name: in
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        '200':
          description: ok
      security:
      - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
components:
  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://api.data.cardiff.ac.uk/authorize
          scopes: {}
